__class__: "<class 'stable_baselines3.dqn.DQN'>"
policy: 'CnnPolicy'
#policy_kwargs:
#  net_arch: !!seq [256, 256]
learning_rate: !!float 5e-4
buffer_size: 15000
learning_starts: 200
batch_size: 36
gamma: !!float 0.99
train_freq: 1
gradient_steps: 1
exploration_fraction: 0.12
exploration_final_eps: 0.01
target_update_interval: 250
verbose: 1
